<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1191" started-at="2016-03-16T21:20:46Z" finished-at="2016-03-16T21:20:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1191" started-at="2016-03-16T21:20:46Z" finished-at="2016-03-16T21:20:47Z">
      <class name="testCases.TC1_CreateShippingTable">
        <test-method status="FAIL" signature="beforeMethod()[pri:0, instance:testCases.TC1_CreateShippingTable@740dc753]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2016-03-16T14:20:46Z" finished-at="2016-03-16T14:20:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utility.ExcelUtils.getRowUsed(ExcelUtils.java:86)
	at utility.ExcelUtils.getRowContains(ExcelUtils.java:71)
	at testCases.TC1_CreateShippingTable.beforeMethod(TC1_CreateShippingTable.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="f()[pri:0, instance:testCases.TC1_CreateShippingTable@740dc753]" name="f" duration-ms="2" started-at="2016-03-16T14:20:47Z" finished-at="2016-03-16T14:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:testCases.TC1_CreateShippingTable@740dc753]" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-03-16T14:20:47Z" finished-at="2016-03-16T14:20:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.TC1_CreateShippingTable -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
